[package]
name = "private-key"
version = "0.1.0"
authors = ["kigi <kigi.chang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sawtk = { path = "../.." }
clap = "2"